import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Cursor from "@/components/common/Cursor";
import Footer from "@/components/common/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Unstop Igniters Club RCCIIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Cursor />
        {children}
        <Footer />
        <script src="three.r134.min.js"></script>
        <script src="vanta.net.min.js"></script>
      </body>
    </html>
  );
}
