import AdminWrapper from "@/components/admin/AdminWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Unstop Igniters Club RCCIIT",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="my-8 min-h-[80vh]">
      <AdminWrapper>{children}</AdminWrapper>
    </div>
  );
}
